pth files were not processed under Debian CPython2 interpreters - by ``gaborbernat``.
